### ISSUE TITLE
Is POSIX API necessary?

### ISSUE THREAD

**Issue by jakobrobert** [tals/audacity-noise-reduction#10]
I have realized that functions specific to the POSIX API are used, especially in Utils.cpp for the SndMap class:

```
#include <sys/stat.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
```

These functions are available under Linux and Mac OS, but not under Windows. I think this is the main reason why I cannot compile the project under Windows. Because I am a Windows user and only have a Linux VM, I would like to compile the project directly under Windows.

Are these functions really necessary or could they be replaced by some standard library functions? What is the purpose of SndMap in general rather than just giving the the file path to sf_open_virtual() directly?

**Comment by tals** [comment]
You're right - I originally added it to speed up read performance and it was just really easy to do it this way, but there isn't a strong justification for that.

`sf_open_virtual` is for implementing a callback-based io (similar to what you had implemented - should've mentioned it but it has been a long while since I've touched it), which uses mmap to do the IO.

This was a lot faster than the built-in `sf_open` when you're things sample-by-sample instead of chunks (which audacity did), [which induces lots of `read(2)` calls](https://github.com/libsndfile/libsndfile/blob/master/src/file_io.c#L333).
Better fixes would've been to implement a buffered reader, or to modify the audacity code to work in chunks.

some possible solutions:
- take a performance hit and just return to `sf_open()`
- implement a buffered reader
- add buffering the audacity code
- only use the mmap version of the reader when you're under linux, otherwise revert back to sf_open (would be slow on windows, but maybe thats acceptable for your situation)

btw, thank you for all those improvements you've been contributing. That's awesome :)

**Comment by jakobrobert** [comment]
I think the last approach is probably the easiest one, I will try that out. I would compile it with Visual Studio under Windows. It should be possible to create a Makefile project in Visual Studio. If I need to make some changes to the Makefile, should I also commit an alternative Makefile for Windows?

You're welcome, it is a fun project 👍🏻 Let me know if you need help with some other projects :)

**Comment by tals** [comment]
I dont think the Makefile will work on windows, actually 😅

You can use CMake or Bazel to have a cross-platform build. They're both a little weird but not too hard to use.
They also have a better story around conditional things so you wouldn't need to duplicate stuff like a Makefile

**Comment by jakobrobert** [comment]
Okay, nice, I will look into CMake. I have a heard from it a lot, I think it is very popular in the C++ community, right?

**Comment by tals** [comment]
CMake is popular, but it's also a pretty prickly system/language so it's not very pleasant to use.
We ended up using it in my last job.

This (pretty cool) project uses both: https://github.com/yse/easy_profiler
so its a good reference point. I find it easier to learn from this than from the official docs

**Comment by jakobrobert** [comment]
Hey @tals , 

I would like to finally begin to add CMake support to the project :)

I am wondering about how to deal with the libsndfile library. I basically see two options. The first is to do it as currently done in the Makefile, i.e. linking to an already installed library. The other option would be to include the source of libsndfile, probably add it as a git submodule. The repository contains a CMake file so this should be easy. It seems to me that linking to an external library is not super straight forward with CMake, often you have to write your own find package scripts, am I correct?

What option would you prefer?

**Comment by tals** [comment]
There's a couple of options :)

- If you want to pick up the external library (like the Makefile does), you can use `find_library` + `target_link_libraries` commands so its not too bad.
- git submodule
- The "modern" way, using a package manager like [Hunter](https://github.com/cpp-pm/hunter) or [Conan](https://conan.io/) (I've only used Hunter, and I remember it being pretty decent).

**Comment by jakobrobert** [comment]
I have now decided for the first method. You are right, it is actually very simple once you know the right commands ;)

I have realized you have two targets in the Makefile, one for the noisereduction driver and one for the tests.
Is it common to add multiple targets for CMake as well or is there some other best practice?
Or is actually the target you pass to the command add_executable the same as the targets in the generated Makefile?

Thanks in advance :)

**Comment by tals** [comment]
yeah its common to have multiple targets :)

you'd create a (static) library (with `add_library`) and link it once to the executable, and again to the tests

**Comment by jakobrobert** [comment]
Okay, thank you :)

And then you would define the name of the exectuable with set_target_properties, am I correct?

**Comment by tals** [comment]
i think it just defaults to the target name

**Comment by jakobrobert** [comment]
I do not really understand what the dist target is used for in the current Makefile. Is it necessary or can I just leave it out in CMake?

**Comment by tals** [comment]
I'd leave it out.

I wouldn't try to port the makefile because it is hairy and doesn't add much value :)

**Comment by jakobrobert** [comment]
I have another question about CMake?

What is the purpose of include_directories, if the include directory is part of the same project? I have seen it in easy_profiler and I wonder because can't you just include the header files by specifying the relative path in the #include directive?

**Comment by tals** [comment]
it's the same as `-I`. You can usually get away with specifying the relative path, as you've said, but not always.

For example maybe the relevant header is generated during build time (RPC frameworks like to do this), so the location where the header is going to end up isn't known ahead of time.
Sometimes people use it for including external libraries instead of a `find_library` like system, which is what the Makefile did.

I think there's other stuff but thats off the top of my head :)

**Comment by jakobrobert** [comment]
Another thing about CMake which i wondered: Are there scenarios where it makes sense to link libraries to an executable publicly? If you link library A to library B publicly, I understand that the interface of library B is propagated to library A. But what would it mean for an executable to have a library propagated to its interface?

**Comment by tals** [comment]
I think it might be an artifact of the abstraction layers - you have multiple types of targets (executable and various libs), and you want to link stuff to them.
The linking mechanism is unified, so no matter the target type, you get to use the same machinery.
And if you're linking stuff, it makes sense to expose these settings to the user, but when you put everything together, you get oddballs like the ones you've described.

There's probably some esoteric use cases for it, but I think the real reason it's there is because it fit their design better.

**Comment by jakobrobert** [comment]
Thank you, I understand :)

**Comment by jakobrobert** [comment]
Is the flag -Wextra important? It does not exist in the MSVC compiler which is used by the default generator on Windows.

**Comment by tals** [comment]
you can just remove it, but in general you can gate those things by platform

**Comment by jakobrobert** [comment]
Okay, thanks.

Another think I wondered: On Windows, I need to add the include directory of libsndfile, for Linux it worked without (and I guess on Mac as well, because the include dir is not specified in the Makefile). Do you know why it works? Do Linux and Mac just add the include dir to the default include dirs automatically when installing the library?

**Comment by tals** [comment]
yup those all have a bunch of header dirs as a first class concept (like `/usr/include/`), so tools tend to pick up on those.

It's a little hard to understand from the cmake docs, but apparently find_library doesn't hook up the include path?
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Find-Libraries#using-external-libraries

**Comment by jakobrobert** [comment]
Definitely I learn a lot about compilers by fixing it for Windows :D It seems to me that clang is far more tolerant than msvc. E.g., msvc requires stdexcept include and definition of M_PI, this is implicit in clang.

**Comment by jakobrobert** [comment]
I am kind of surprised, that clang even allows to use variable number arguments for stack-allocated arrays :D 

As e.g. done in https://github.com/tals/audacity-noise-reduction/blob/fa6f5ad147cc1a724afa51f2199120547ffbe8a3/noisereduction/TrackUtils.cpp#L34

Couldn't this easily lead to stack overflows? It seems paradox to me to allocate something on the stack if the size is not known at compile time.

**Comment by tals** [comment]
You could overflow the stack sure, but you can overflow lots of things :)

In general you don't want to allocate a ton there because the default sizes aren't huge (like 512kb on mac/linux and 1mb in Windows. you can request that your thread has more stack size).

But just for the technical "allocation" aspect of the stack, you don't need to know the size ahead of time since you're just using a pointer to manage a preallocated slab of memory

**Comment by Jack-42** [comment]
> 
> 
> it's the same as `-I`. You can usually get away with specifying the relative path, as you've said, but not always.
> 
> For example maybe the relevant header is generated during build time (RPC frameworks like to do this), so the location where the header is going to end up isn't known ahead of time.
> Sometimes people use it for including external libraries instead of a `find_library` like system, which is what the Makefile did.
> 
> I think there's other stuff but thats off the top of my head :)

Btw, I now found out that the header files are not shown in Visual Studio if you do not add them. So I guess it is good practice to always add them even if it can be compiled without.

**Comment by jakobrobert** [comment]
I have almost finished, but have a very strange error still.

It compiles fine, but when I run it under Windows, it tells me "cannot find libsndfile-1.dll". This is strange, because in the CMake build process it definitely finds the file libsndfile-1.lib. So I wonder why it is even looking for a dll at runtime.

Have you heard of a similar issue once?

**Comment by tals** [comment]
Yeah. On Windows a lib can sometimes just contain dynamic linking information, providing little value.
You can tell that is the case by just examining the size of the lib file and seeing that it’s quite small (you can splunk into it with objdump and its ilk).

**Comment by jakobrobert** [comment]
Thank you very much :) This should be the reason, the lib only has 10 kb while the dll has 1.7 mb. I am starting to understand why many developers do not like using Windows, the library and package management seems to be much easier on Unix-based systems :D

But then, what is even the purpose of the .lib if you have to link the .dll anyway?

**Comment by tals** [comment]
I think nowadays it just tells it what symbols to expect in the dll and what its name is.
You can totally just generate that from the dll, but for some reason its typically done like this in Windows.
I wouldn't be surprised if there's some historical justification for it :)

**Comment by jakobrobert** [comment]
Okay, thanks 👍 
 
I think I am understanding now. The .lib is necessary for the linker to resolve the external symbols, but the actual implementation is loaded at runtime from a dll.

I have now created a hack to just copy the dll to the executable dir with a batch file, better than doing it by hand at least :D
